---
- name: Deploy VM 
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a VM from a template
      vmware_guest:
        hostname: "vcenter.halehouse.org"
        validate_certs: False
        datacenter: Home
        cluster: Lab
        name: FreeSatellite
        template: centos7-template
        folder: /Home/vm
        hardware:
          memory_mb: 4096
          num_cpus: 1
        networks:
        - name: "VM Network"
          ip: 192.168.1.150
          netmask: 255.255.255.0
          gateway: 192.168.1.254
          domain: halehouse.org
          dns_servers:
          - 192.168.1.254
        customization:
          dns_servers:
          - 192.168.1.254
          domain: halehouse.org
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy
